import {
  Activity,
  AlertTriangle,
  Archive,
  Ban,
  BookOpen,
  Bug,
  Building2,
  CheckCircle2,
  Cpu,
  Eye,
  FlaskConical,
  Gauge,
  Layers,
  Lightbulb,
  Mic,
  Network,
  Pin,
  ScrollText,
  Search,
  Shield,
  Shuffle,
  Sparkles,
  SquareDashedBottom,
  TrendingUp,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/** Icon lookup for section panels, keyed by the names used in lib/section-presentation.ts. */
export const SECTION_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertTriangle,
  archive: Archive,
  ban: Ban,
  book: BookOpen,
  bug: Bug,
  building: Building2,
  check: CheckCircle2,
  corner: SquareDashedBottom,
  cpu: Cpu,
  eye: Eye,
  flask: FlaskConical,
  gauge: Gauge,
  layers: Layers,
  lightbulb: Lightbulb,
  mic: Mic,
  network: Network,
  pin: Pin,
  scroll: ScrollText,
  search: Search,
  shield: Shield,
  shuffle: Shuffle,
  sparkles: Sparkles,
  trending: TrendingUp,
  wrench: Wrench,
};
